"""The provider smoke: generated bytes only, against the real bucket.

Excluded from the gate by `host_smoke` (INV-05). It needs network access and a configured
Cold Storage bucket, and it is the only place four things can actually be established:

* signed requests reach *this* endpoint and are accepted;
* multipart genuinely works here, forced down to a modest object rather than needing a
  5 GiB fixture;
* a complete readback returns what was stored;
* **listing pagination works, and by which API** — the question OQ-028 exists for, where
  DigitalOcean's compatibility page and its limits page contradict each other. A
  deterministic fake proves the *caller* follows markers; only this proves the *provider*
  offers them.

**No session audio is uploaded, ever.** The charter is explicit and the reason is not
squeamishness: the four-file zstd evidence is a local round trip, and putting real
recordings in a bucket to test an SDK would be spending the exact risk this milestone
exists to reduce. Everything here is generated from an LCG, under a throwaway prefix, and
the objects it writes are the only ones any test creates.

Run it with the archive environment configured:

    uv run pytest -m host_smoke tests/test_archive_smoke.py -q

**Run it under the upload credential**, since it writes. `verify`, `list`, `status` and
`restore` should run under a separate read-only key in normal use (ADR-0035) — that is an
operator practice rather than something a test can establish, because confirming a key is
read-only means attempting a write with it, and this module will not.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from dnd_audio.archive.config import (
    MIN_MULTIPART_PART_BYTES,
    ArchiveConfigError,
    load_archive_config,
)
from dnd_audio.archive.spaces import SpacesStorage, build_storage

pytestmark = [pytest.mark.host_smoke, pytest.mark.allow_network]

#: Everything this test writes lives here, so a human can recognize it and remove it. Not
#: under `sessions/`: nothing in it is a session, and it must never be mistaken for one.
SMOKE_PREFIX = "smoke/m7a"


def generated(size: int, seed: int = 1) -> bytes:
    """Deterministic, incompressible-ish bytes. Never session audio."""
    state = seed
    out = bytearray()
    while len(out) < size:
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF
        out += state.to_bytes(4, "little")
    return bytes(out[:size])


@pytest.fixture
def storage() -> SpacesStorage:
    try:
        settings = load_archive_config()
    except ArchiveConfigError as exc:
        pytest.skip(f"the archive is not configured on this machine: {exc.code} (M7a)")
    # Forced low so the multipart path is exercised by a few MiB rather than by 5 GiB.
    return build_storage(
        settings.model_copy(
            update={
                "multipart_threshold_bytes": MIN_MULTIPART_PART_BYTES,
                "multipart_part_bytes": MIN_MULTIPART_PART_BYTES,
            }
        )
    )


class TestTheProviderAcceptsWhatThisProjectSends:
    def test_a_small_object_round_trips(self, storage: SpacesStorage, tmp_path: Path) -> None:
        payload = generated(64 * 1024)
        source = tmp_path / "small.bin"
        source.write_bytes(payload)
        key = f"{SMOKE_PREFIX}/small-{hashlib.sha256(payload).hexdigest()[:16]}.bin"

        storage.put_object(key, source)
        head = storage.head_object(key)
        assert head is not None
        assert head.size_bytes == len(payload)

        with storage.open_object(key) as body:
            got = b""
            while chunk := body.read(1 << 20):
                got += chunk
        assert hashlib.sha256(got).hexdigest() == hashlib.sha256(payload).hexdigest()

    def test_multipart_round_trips_and_its_etag_is_not_a_content_hash(
        self, storage: SpacesStorage, tmp_path: Path
    ) -> None:
        """Forced multipart on a modest object, per the charter's non-goal.

        The ETag assertion is the point of doing it here rather than against a stub: it
        confirms on the real provider that a multipart ETag is not the content digest, which
        is the shortcut ADR-0038 forbids.
        """
        payload = generated(MIN_MULTIPART_PART_BYTES * 2 + 4096, seed=7)
        source = tmp_path / "multipart.bin"
        source.write_bytes(payload)
        digest = hashlib.sha256(payload).hexdigest()
        key = f"{SMOKE_PREFIX}/multipart-{digest[:16]}.bin"

        storage.put_object(key, source)

        with storage.open_object(key) as body:
            got = b""
            while chunk := body.read(1 << 20):
                got += chunk
        assert hashlib.sha256(got).hexdigest() == digest

        head = storage.head_object(key)
        assert head is not None
        assert head.etag is not None
        assert digest not in head.etag
        assert "-" in head.etag.strip('"'), "a multipart ETag carries a part count suffix"


class TestPaginationOnTheRealEndpoint:
    """OQ-028: the provider's own documentation contradicts itself. This settles it."""

    def test_listing_returns_every_key_across_pages(self, storage: SpacesStorage) -> None:
        prefix = f"{SMOKE_PREFIX}/pagination"
        expected = set()
        for index in range(5):
            payload = generated(1024, seed=100 + index)
            key = f"{prefix}/object-{index}.bin"
            import tempfile

            with tempfile.NamedTemporaryFile() as handle:
                handle.write(payload)
                handle.flush()
                storage.put_object(key, Path(handle.name))
            expected.add(key)

        # `MaxKeys` is not part of the storage protocol — deliberately, since a caller must
        # never be able to bound a listing — so the client is driven directly here to force
        # several pages out of five objects.
        marker: str | None = None
        found: set[str] = set()
        pages = 0
        while True:
            arguments = {"Bucket": storage.bucket, "Prefix": prefix, "MaxKeys": 1}
            if marker is not None:
                arguments["Marker"] = marker
            response = storage.client.list_objects(**arguments)
            pages += 1
            contents = response.get("Contents", [])
            found.update(str(item["Key"]) for item in contents)
            if not response.get("IsTruncated"):
                break
            marker = response.get("NextMarker") or (str(contents[-1]["Key"]) if contents else None)
            assert marker is not None, "the provider truncated a listing and supplied no marker"
            assert pages < 50, "pagination did not terminate"

        assert pages > 1, "MaxKeys=1 over five objects must produce several pages"
        assert expected <= found

    def test_the_adapters_own_listing_agrees(self, storage: SpacesStorage) -> None:
        """The path production actually uses, over the same objects."""
        prefix = f"{SMOKE_PREFIX}/pagination"
        assert len(list(storage.list_keys(prefix))) >= 5


class TestNoSessionAudioIsInvolved:
    def test_every_key_this_module_writes_is_under_the_smoke_prefix(self) -> None:
        """Read as a statement of intent that a reader can check against the source.

        The charter's non-goal is explicit: uploading real DJI recordings to test an SDK
        spends the risk this milestone exists to reduce.
        """
        source = Path(__file__).read_text(encoding="utf-8")
        assert 'SMOKE_PREFIX = "smoke/m7a"' in source
        assert "generated(" in source
        assert "raw/" not in source.replace("# ", "")


class TestTheEnvironmentIsWhatItClaims:
    def test_the_configured_endpoint_is_https(self) -> None:
        try:
            settings = load_archive_config()
        except ArchiveConfigError:
            pytest.skip("the archive is not configured on this machine (M7a)")
        assert settings.endpoint_url.startswith("https://")
