"""The provider smoke: generated bytes only, against the real bucket.

Excluded from the gate by `host_smoke` (INV-05). It needs network access and a configured
Cold Storage bucket, and it is the only place four things can actually be established:

* signed requests reach *this* endpoint and are accepted;
* multipart genuinely works here, forced down to a modest object rather than needing a
  5 GiB fixture;
* a complete readback returns what was stored;
* **listing pagination works, and by which API** — the question OQ-028 exists for, where
  DigitalOcean's compatibility page and its limits page contradict each other. A
  deterministic fake proves the *caller* follows markers; only this proves the *provider*
  offers them.

**No session audio is uploaded, ever.** The charter is explicit and the reason is not
squeamishness: the four-file zstd evidence is a local round trip, and putting real
recordings in a bucket to test an SDK would be spending the exact risk this milestone
exists to reduce. Everything here is generated from an LCG, under a throwaway prefix, and
the objects it writes are the only ones any test creates.

Run it with the archive environment configured:

    uv run pytest -m host_smoke tests/test_archive_smoke.py -q

**Run it under the upload credential**, since it writes. `verify`, `list`, `status` and
`restore` should run under a separate read-only key in normal use (ADR-0035) — that is an
operator practice rather than something a test can establish, because confirming a key is
read-only means attempting a write with it, and this module will not.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest

if TYPE_CHECKING:
    import numpy as np

from dnd_audio.archive.config import (
    MIN_MULTIPART_PART_BYTES,
    ArchiveConfigError,
    load_archive_config,
)
from dnd_audio.archive.spaces import SpacesStorage, build_storage

pytestmark = [pytest.mark.host_smoke, pytest.mark.allow_network]

#: Everything this test writes lives here, so a human can recognize it and remove it. Not
#: under `sessions/`: nothing in it is a session, and it must never be mistaken for one.
SMOKE_PREFIX = "smoke/m7a"


def generated(size: int, seed: int = 1) -> bytes:
    """Deterministic, incompressible-ish bytes. Never session audio."""
    state = seed
    out = bytearray()
    while len(out) < size:
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF
        out += state.to_bytes(4, "little")
    return bytes(out[:size])


def synthetic_samples(count: int, seed: int = 1) -> np.ndarray[Any, Any]:
    """A short float32 waveform, synthesized here. Quiet noise, not anyone's voice."""
    import numpy as np

    state = np.random.default_rng(seed)
    return (state.standard_normal(count) * 0.01).astype(np.float32)


@pytest.fixture
def storage() -> SpacesStorage:
    try:
        settings = load_archive_config()
    except ArchiveConfigError as exc:
        pytest.skip(f"the archive is not configured on this machine: {exc.code} (M7a)")
    # Forced low so the multipart path is exercised by a few MiB rather than by 5 GiB.
    return build_storage(
        settings.model_copy(
            update={
                "multipart_threshold_bytes": MIN_MULTIPART_PART_BYTES,
                "multipart_part_bytes": MIN_MULTIPART_PART_BYTES,
            }
        )
    )


class TestTheProviderAcceptsWhatThisProjectSends:
    def test_a_small_object_round_trips(self, storage: SpacesStorage, tmp_path: Path) -> None:
        payload = generated(64 * 1024)
        source = tmp_path / "small.bin"
        source.write_bytes(payload)
        key = f"{SMOKE_PREFIX}/small-{hashlib.sha256(payload).hexdigest()[:16]}.bin"

        storage.put_object(key, source)
        head = storage.head_object(key)
        assert head is not None
        assert head.size_bytes == len(payload)

        with storage.open_object(key) as body:
            got = b""
            while chunk := body.read(1 << 20):
                got += chunk
        assert hashlib.sha256(got).hexdigest() == hashlib.sha256(payload).hexdigest()

    def test_multipart_round_trips_and_its_etag_is_not_a_content_hash(
        self, storage: SpacesStorage, tmp_path: Path
    ) -> None:
        """Forced multipart on a modest object, per the charter's non-goal.

        The ETag assertion is the point of doing it here rather than against a stub: it
        confirms on the real provider that a multipart ETag is not the content digest, which
        is the shortcut ADR-0038 forbids.
        """
        payload = generated(MIN_MULTIPART_PART_BYTES * 2 + 4096, seed=7)
        source = tmp_path / "multipart.bin"
        source.write_bytes(payload)
        digest = hashlib.sha256(payload).hexdigest()
        key = f"{SMOKE_PREFIX}/multipart-{digest[:16]}.bin"

        storage.put_object(key, source)

        with storage.open_object(key) as body:
            got = b""
            while chunk := body.read(1 << 20):
                got += chunk
        assert hashlib.sha256(got).hexdigest() == digest

        head = storage.head_object(key)
        assert head is not None
        assert head.etag is not None
        assert digest not in head.etag
        assert "-" in head.etag.strip('"'), "a multipart ETag carries a part count suffix"


class TestPaginationOnTheRealEndpoint:
    """OQ-028: the provider's own documentation contradicts itself. This settles it."""

    def test_listing_returns_every_key_across_pages(self, storage: SpacesStorage) -> None:
        prefix = f"{SMOKE_PREFIX}/pagination"
        expected = set()
        for index in range(5):
            payload = generated(1024, seed=100 + index)
            key = f"{prefix}/object-{index}.bin"
            import tempfile

            with tempfile.NamedTemporaryFile() as handle:
                handle.write(payload)
                handle.flush()
                storage.put_object(key, Path(handle.name))
            expected.add(key)

        # `MaxKeys` is not part of the storage protocol — deliberately, since a caller must
        # never be able to bound a listing — so the client is driven directly here to force
        # several pages out of five objects.
        marker: str | None = None
        found: set[str] = set()
        pages = 0
        while True:
            arguments = {"Bucket": storage.bucket, "Prefix": prefix, "MaxKeys": 1}
            if marker is not None:
                arguments["Marker"] = marker
            response = storage.client.list_objects(**arguments)
            pages += 1
            contents = response.get("Contents", [])
            found.update(str(item["Key"]) for item in contents)
            if not response.get("IsTruncated"):
                break
            marker = response.get("NextMarker") or (str(contents[-1]["Key"]) if contents else None)
            assert marker is not None, "the provider truncated a listing and supplied no marker"
            assert pages < 50, "pagination did not terminate"

        assert pages > 1, "MaxKeys=1 over five objects must produce several pages"
        assert expected <= found

    def test_the_adapters_own_listing_agrees(self, storage: SpacesStorage) -> None:
        """The path production actually uses, over the same objects."""
        prefix = f"{SMOKE_PREFIX}/pagination"
        assert len(list(storage.list_keys(prefix))) >= 5


class TestNoSessionAudioIsInvolved:
    def test_the_audio_this_module_uploads_is_synthesized_here(self, tmp_path: Path) -> None:
        """The charter's non-goal, checked rather than asserted about the source text.

        The first version scanned this file for the string `raw/` — which broke the moment
        the module legitimately built a session with a `raw/` directory, and which was
        never evidence of anything anyway: it read the test, not the bytes. What actually
        matters is that every byte sent is generated in this process from a seeded
        sequence, so this synthesizes a file and asserts its content is exactly that.
        """
        from dnd_audio.fixtures.wav import write_wav

        path = tmp_path / "probe.wav"
        samples = synthetic_samples(1000, seed=5)
        write_wav(path, samples, sample_rate=48_000)

        raw = path.read_bytes()
        assert raw[:4] == b"RIFF"
        assert samples.tobytes() in raw, "the audio must be the sequence generated here"

    def test_uploads_are_confined_to_the_smoke_prefix_or_a_throwaway_session(self) -> None:
        """Two prefixes are written by this module, and both are disposable."""
        assert SMOKE_PREFIX.startswith("smoke/")
        assert not SMOKE_PREFIX.startswith("sessions/")


class TestTheEnvironmentIsWhatItClaims:
    def test_the_configured_endpoint_is_https(self) -> None:
        try:
            settings = load_archive_config()
        except ArchiveConfigError:
            pytest.skip("the archive is not configured on this machine (M7a)")
        assert settings.endpoint_url.startswith("https://")


class TestTheRealDrillAgainstTheRealBucket:
    """`upload` → `verify` → remote-only `restore`, end to end, on generated bytes.

    The first version of this module exercised `put`/`get`/`list` directly and stopped
    there — so it proved the *adapter* talks to DigitalOcean and proved nothing about the
    completion gate's actual claim, which is that a session round-trips through the commit
    protocol and restores from the session id alone. Found by M7a's code review.

    The session it builds is synthetic in every part: generated bytes in files named like
    recordings, never real audio. That keeps the charter's non-goal intact while exercising
    the same code path a real session takes.
    """

    def build_session(self, root: Path, session_id: str) -> Path:
        """A minimal but genuine session: `session.yaml`, two tracks, synthesized audio.

        Real WAV containers, because `inspect` runs FFprobe over them and the archive
        requires a current manifest — generated bytes with a `.wav` name are refused, as
        they should be. The *audio* is a seeded noise sequence synthesized in this process:
        no session recording is uploaded, which is the charter's non-goal.
        """
        import yaml

        from dnd_audio.fixtures.wav import BroadcastMetadata, write_wav

        session_dir = root / "smoke-session"
        for index, track in enumerate(("tx-a", "tx-b")):
            directory = session_dir / "raw" / track
            directory.mkdir(parents=True)
            write_wav(
                directory / f"TX0{index + 1}_MIC001_20260815_190000_orig.wav",
                synthetic_samples(24_000, seed=200 + index),
                sample_rate=48_000,
                # A `bext` time reference, because `inspect` refuses to invent timing
                # (INV-12) and the archive requires a current manifest. Frame-quantized to
                # 1600 samples like the real hardware writes (OQ-004), so the session this
                # exercises has the shape a real one does.
                broadcast=BroadcastMetadata(time_reference=1600 * (100 + index)),
            )
        (session_dir / "raw" / "field-notes.txt").write_bytes(generated(1024, seed=42))

        document = {
            "session_id": session_id,
            "title": "M7a provider smoke",
            "tracks": [
                {
                    "track_id": track,
                    "receiver_id": "rx-a",
                    "receiver_channel": index + 1,
                    "speaker_id": f"speaker-{track}",
                    "speaker_name": f"Speaker {track}",
                    "input": f"raw/{track}",
                }
                for index, track in enumerate(("tx-a", "tx-b"))
            ],
        }
        (session_dir / "session.yaml").write_text(
            yaml.safe_dump(document, sort_keys=False), encoding="utf-8"
        )
        return session_dir

    def test_upload_verify_and_remote_only_restore(
        self, storage: SpacesStorage, tmp_path: Path
    ) -> None:
        import shutil

        from dnd_audio.archive.report import OperationStatus, VerificationState
        from dnd_audio.archive.runner import run_list, run_restore, run_upload, run_verify
        from dnd_audio.determinism import sha256_file
        from dnd_audio.inspection.runner import run_inspect

        # A distinct id per run, so a re-run is never blocked by its own previous commit
        # and never touches another run's objects.
        session_id = f"m7a-smoke-{hashlib.sha256(str(tmp_path).encode()).hexdigest()[:12]}"
        session_dir = self.build_session(tmp_path, session_id)

        assert run_inspect(session_dir).exit_code == 0

        expected = {
            path.relative_to(session_dir).as_posix(): sha256_file(path)
            for path in sorted((session_dir / "raw").rglob("*"))
            if path.is_file()
        }

        uploaded = run_upload(session_dir, storage=storage, lock_dir=tmp_path / "locks")
        assert uploaded.status is OperationStatus.COMPLETE, uploaded.errors
        assert uploaded.verification is VerificationState.VERIFIED

        assert session_id in run_list(storage=storage)[0]

        verified = run_verify(session_id, storage=storage)
        assert verified.status is OperationStatus.COMPLETE, verified.errors
        assert verified.verification is VerificationState.VERIFIED

        # The disaster: nothing local survives.
        shutil.rmtree(session_dir)

        destination = tmp_path / "recovered"
        destination.mkdir()
        restored = run_restore(session_id, destination, storage=storage)
        assert restored.status is OperationStatus.COMPLETE, restored.errors

        rebuilt = {
            path.relative_to(destination).as_posix(): sha256_file(path)
            for path in sorted(destination.rglob("*"))
            if path.is_file()
        }
        assert rebuilt == expected

    def test_a_track_scope_restores_only_that_track(
        self, storage: SpacesStorage, tmp_path: Path
    ) -> None:
        from dnd_audio.archive.report import OperationStatus
        from dnd_audio.archive.runner import run_restore, run_upload
        from dnd_audio.inspection.runner import run_inspect

        session_id = f"m7a-track-{hashlib.sha256(str(tmp_path).encode()).hexdigest()[:12]}"
        session_dir = self.build_session(tmp_path, session_id)
        assert run_inspect(session_dir).exit_code == 0
        assert (
            run_upload(session_dir, storage=storage, lock_dir=tmp_path / "locks").status
            is OperationStatus.COMPLETE
        )

        destination = tmp_path / "one-track"
        destination.mkdir()
        report = run_restore(session_id, destination, storage=storage, track_id="tx-a")
        assert report.status is OperationStatus.COMPLETE

        restored = [
            path.relative_to(destination).as_posix()
            for path in sorted(destination.rglob("*"))
            if path.is_file()
        ]
        assert restored
        assert all(path.startswith("raw/tx-a/") for path in restored)
        # The unassigned file is recovered only by a whole-session restore (INV-11).
        assert not (destination / "raw" / "field-notes.txt").exists()
